### ISSUE TITLE
print '%(name)s: %(endpoint)s' % {  ^ SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by TZubiri** [TZubiri/issue_box#1]
Running the following command:

aws --version

Returns the following error

Traceback (most recent call last):
  File "/home/tomas/.local/bin/aws", line 6, in <module>
    from aws.main import main
  File "/home/tomas/.local/lib/python3.6/site-packages/aws/main.py", line 23
    print '%(name)s: %(endpoint)s' % {
                                 ^
SyntaxError: invalid syntax

**Comment by TZubiri** [comment]
What's happening here is that the user installed a pip package called aws, the official package is called awscli.

Workaround:

pip uninstall aws
pip install awscli

**Comment by TZubiri** [comment]
There's several parties that dropped the ball for such an unhelpful error message to arise:

1- Python: This is python2 code running in python3. At the very least python3 should suggest something that hints that at this being a python2 syntax feature. If this were a python 2 interpreter running python3 code, maybe I'd give them a bit more leeway, but there's no excuse for the compiler to play dumb here. Anyway's, this is the only thing I can nail them down on for now, but I'm sure this is just the tip of the iceberg for python, the 2 to 3 transition was infamously untidy.

2- Pypi: This is a subset of python, btw, but I want to be more precise. Pypi here is allowing a problematic package to persist despite lack of updates for god knows how long, all with the potential excuse of backwards compatibility, in case there's scripts that depend on this running pip install aws. I can sympathize with that, but not too greatly, break backwards compatibility here, make aws an alias of awscli.

3- PIP: I might be threading too much in the internals of python, but it must be said that PIP and the package index are probably maintained by difference teams. Ok, python itself doesn't emit a cool warning, and pypi did nothing about the trash package, but this is an issue that the pip tool itself could have taken care of during the installation of a python2 package on a python3 distribution.
 
4- Amazon has 613k employees, are you telling me none of them contribute to python? None of them have contacts in Pypi? You can't put one of those developers on a project that's important to pypi in exchange for the aws package name?
